#!/bin/bash
buildMpop() {
	./autogen.sh || { echo "autogen.sh failed"; exit 1; }
	./configure --enable-specialapi --enable-mail --enable-perl --enable-spamdelclient --enable-uri-list --enable-wap --enable-kav8 --enable-kas5 --with-db4-compat --enable-utf --enable-ameli || { echo "configure failed"; exit 1; }
	make -j 4
	sudo make install
	/etc/init.d/httpd restart
}

BRANCH=$1

if [ -z $BRANCH ]
then
	echo "Give me mpop branch name";
fi

pushd ~/mpop/ > /dev/null

gitgo $BRANCH && buildMpop

popd > /dev/null