#!/bin/sh

. /etc/rc.d/init.d/functions

# Creamos un fichero PID para monit
SCRIPT="$(basename $0)"
PIDFILE="/var/run/$SCRIPT.pid"
ps -fe | grep "$SCRIPT" | head -n1 | cut -d" " -f 6 > ${PIDFILE}

USER="root" # FIXME, it must be "mail"

DAEMON="/usr/local/bin/node"
ROOT_DIR="/usr/local/fest/"

SERVER="$ROOT_DIR/lib/proxy.js"
LOG_FILE="/var/log/$SCRIPT.log"

LOCK_FILE="/var/lock/subsys/$SCRIPT"

CONFIG="/etc/fest.conf"

do_start()
{
        if [ ! -f "$LOCK_FILE" ] ; then
                echo -n $"Starting $SERVER: "
                #/sbin/runuser -l "$USER" -c "$DAEMON $SERVER >> $LOG_FILE &" && echo_success || echo_failure

		if [ ! -f "$LOG_FILE" ]
		then
			touch "$LOG_FILE"
			chown "$USER" "$LOG_FILE"
		fi

		su -m "$USER" -c "nohup $DAEMON $SERVER $CONFIG >> $LOG_FILE &" && echo_success || echo_failure
                RETVAL=$?
                echo
                [ $RETVAL -eq 0 ] && touch $LOCK_FILE
        else
                echo "$SERVER is locked."
                RETVAL=1
        fi
}
do_stop()
{
        echo -n $"Stopping $SERVER: "
        PID=`ps -fe | grep "$SCRIPT" | grep -v "$0" | grep -v grep | head -n1  | awk '{print $2}'`
        kill -9 $PID > /dev/null 2>&1 && echo_success || echo_failure

        if [ -f ${PIDFILE} ]; then
        	rm ${PIDFILE}
        fi
        RETVAL=$?

        echo
        [ $RETVAL -eq 0 ] && rm -f $LOCK_FILE
}

case "$1" in
        start)
                do_start
                ;;
        stop)
                do_stop
                ;;
        restart)
                do_stop
		do_start
                ;;
        *)
                echo "Usage: $0 {start|stop|restart}"
                RETVAL=1
esac

exit $RETVAL
